name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build-job:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: building
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
      - run: pip install meson
      - name: setup build dir
      - run: meson setup build -Dgui=true -Dtest=enabled
      - name: building
      - run: meson compile -C build
      - name: running test executable
      - run: ./build/tests/test_main
